#!/bin/bash

#Programm, mis prindib kuupäeva ja kellaaja ning salvestab vajalikud andmed
#faili sisse.

Kokku=`date`;

Kuu=`date | awk -F" " '{ print $2 }'`;

Kuup2ev=`date | awk -F" " '{ print $3 }'`;

P2ev=`date | awk -F" " '{ print $1 }'`;

Kellaaeg=`date | awk -F" " '{ print $4 }'`;

Riik=`date | awk -F" " '{ Print $5 }'`;

Aasta=`date | awk -F" " '{ Print $6 }'`;

Number=`date | awk -F" " '{ Print $4 }' | awk -F: '{ print $2 }'`;

# echo k2sk peab olema yhe reaga

echo "T2nane kuup2ev on ${Kuu} ${Kuup2ev} ${Aasta}. Kell on ${Kellaaeg}. See on ${Riik} aeg." >/root/temp/cron_proov${Number}.txt
