#!/bin/bash

#PHP paigaldamiseks skript

PHP=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed")

if [ $PHP -eq 0 ]; then

echo "Paigaldame PHP"
apt-get install -y php5-mysql
elif [ $PHP -eq 1 ]; then
echo "PHP on paigaldatud!"
fi
